### ISSUE TITLE
implement close function

### ISSUE THREAD

**Issue by cblgh** [cabal-club/cabal-core#26]
we need to be able to close an opened cabal

this would close the underlying kappa-core and stop replication

--------------------------------------

Breakdown:

- [ ] implement `multifeed#close` (using `hypercore#close`) https://github.com/noffle/multifeed/issues/10
- [ ] implement some way to stop/terminate a `multifeed-index` that's running
- [ ] implement `kappa-core#close`, which 1) stops all indexes, and then 2) stops the `multifeed` 
- [ ] decide how the APIs of all of the above modules should respond when you try to use them AFTER they've been closed

**Comment by noffle** [comment]
this is a fun series of PRs:

- implement multifeed#close (using hypercore#close)
- implement some way to stop/terminate a multifeed-index that's running
- implement kappa-core#close, which 1) stops all indexes, and then 2) stops the multifeed
- decide how the APIs of all of the above modules should respond when you try to use them AFTER they've been closed

**Comment by ralphtheninja** [comment]
Tried to edit @noffle 's post but apparently email replies can't have markdown :)

- [ ] implement multifeed#close (using hypercore#close) 
- [ ] implement some way to stop/terminate a multifeed-index that's running
- [ ] implement kappa-core#close, which 1) stops all indexes, and then 2) stops the multifeed 
- [ ] decide how the APIs of all of the above modules should respond when you try to use them AFTER they've been closed

**Comment by noffle** [comment]
We did this!
