### ISSUE TITLE
Discovery key leaking chats?

### ISSUE THREAD

**Issue by msfeldstein** [cabal-club/cabal-core#35]
Should we be using a hash of the cabal's key as the discovery key, rather than the key itself?  I could be wrong but it sounds like discovery keys can be sniffed on discovery networks, so most chats would be effectively public.
https://github.com/cabal-club/cabal-core/blob/master/swarm.js#L6

Dat uses hypercores discovery key which is a hash to keep the actual dat key private, as seen here: https://github.com/mafintosh/hypercore/blob/master/index.js#L57
https://docs.datproject.org/docs/security-faq#is-it-possible-to-discover-read-keys-via-man-in-the-middle

**Comment by noffle** [comment]
I've been thinking about this too.

Right now cabals aren't encrypted, so anyone who can find peers for a
cabal can read its contents.

If we did start encrypting messages to the cabal key, then I think yes,
it'd make sense to do discovery on a separate key (like its hash)!

**Comment by noffle** [comment]
Actually, we're really close to having encrypted cabals! We just need to
get @telamon's PR into multifeed: https://github.com/kappa-db/multifeed/pull/18

**Comment by karissa** [comment]
Hashing the key to create the discovery key sounds like a good idea. Clients would need to upgrade but it would be worth it.

**Comment by karissa** [comment]
Discovery on a separate key would also be a big short term win that increase privacy in the short term, and could be done before the encryption pr goes live.
The encryption pr looks good though!

**Comment by telamon** [comment]
Give me a holler if i can help, I'll be lurking in the background for now.

**Comment by karissa** [comment]
Thanks @telamon! PRs definitely welcome!

**Comment by noffle** [comment]
Confirmed that we do hash the cabal key before swarming on it (in `discovery-swarm`).
