### ISSUE TITLE
Direct messaging

### ISSUE THREAD

**Issue by nikolaiwarner** [cabal-club/cabal-core#4]
It would be useful sometimes to have a one-on-one conversation with another user. Would it possible to create a concept of a direct message? 

Perhaps it's just a special channel for the two participants. I'm guessing everyone connected to a cabal can read every message so it may not be private but it still might be a useful feature. 

Would it be possible to encrypt a message before it's sent so that only a single recipient may read it? The rest of the cabal would be there to help get the message to its destination but couldnt read the contents.

**Comment by noffle** [comment]
> Would it be possible to encrypt a message before it's sent so that only a single recipient may read it?

Yes! This is how other p2p systems like [SSB](https://www.scuttlebutt.nz/concepts/private-message.html) and [BitMessage](https://bitmessage.org/wiki/Main_Page) do private messages. We might be able to use [private-box](https://github.com/auditdrivencrypto/private-box), if our hypercore keys (also sodium-based!) are compatible with private-box's.

**Comment by cblgh** [comment]
YES

**Comment by noffle** [comment]
I've started working on the cabal-core portion of this feature.

**Comment by hackergrrl** [comment]
We did it. ✌🏻
