### ISSUE TITLE
Replication handshake

### ISSUE THREAD

**Issue by noffle** [cabal-club/cabal-core#40]
It would be really nice if both peers, before replicating, could exchange metadata about themselves and decide whether *to* sync. I wrote something for doing just this for Mapeo called [handshake-stream](https://github.com/noffle/handshake-stream). For now, the payload could just be a cabal protocol version string.

This would let clients potentially show meaningful sync errors, and also avoid showing peers by their pubkey on the sidebar when we aren't even replicating with them.

**Comment by dwblair** [comment]
I love this idea -- and I'm going to check out handshake-stream!

In my experience of experimenting with cabal with friends: when we don't connect, I then wonder where the fail point is:  am I myself unable to reach the outside world?  And/or is the 'bootstrapping node' online?  Is the other peer online?  

There are some nice diagnostics bundled into [dat-doctor](https://github.com/datproject/dat-doctor) that feel perhaps relevant ... 

... but maybe none of this is within scope of the (already useful) feature you're describing here ...

**Comment by cblgh** [comment]
ohhh ohhh could we have clients tell others what version of cabal-core they are running in the handshake? that would be great for implementing a feature that let's people know that "hey your peers are using a newer version of cabal-core!"

**Comment by noffle** [comment]
Yes!

**Comment by noffle** [comment]
Closing, since we now have hypercore extensions for ephemeral message passing between peers!
