### ISSUE TITLE
Protocol encryption

### ISSUE THREAD

**Issue by noffle** [cabal-club/cabal-core#49]
multifeed supports an encryption keys via `opts.key`. We just need to add the plumbing so cabal-core offers  way to pass it in by clients.

**Comment by cblgh** [comment]
For at-rest or transport? (I know work has been done w/ both but _gawd_ at-rest would be so rad/{cyber,lunar}punk)

**Comment by noffle** [comment]
oh! This is for transport.

**Comment by noffle** [comment]
We did this! :+1:
