### ISSUE TITLE
Sparse replication?

### ISSUE THREAD

**Issue by jimpick** [cabal-club/cabal-core#5]
I think it would make sense to pass the "sparse: true" flag to hyperdb for normal clients. If a cabal dat has a lot of history, that might take a long time to download.

For seeders, it probably makes sense to have "sparse: false" so they archive the complete history of a chat.

**Comment by karissa** [comment]
yeah makes sense!

**Comment by hackergrrl** [comment]
We'll finally be getting this feature in the next generation of Cabal: [cable](https://github.com/cabal-club/cable). 🔥
