### ISSUE TITLE
handle hypercore replication timeouts

### ISSUE THREAD

**Issue by cblgh** [cabal-club/cabal-core#58]
originally suggested by @substack, it seems we have a few connectivity issues for sessions that are open for a long amount of time. 

by adding a timeout to the replication stream, we can likely solve the problems we've been seeing

### implementation
* upgrade to [`hypercore@8`](https://github.com/mafintosh/hypercore)
* solve the issue with the following [`hypercore-protocol`](https://github.com/mafintosh/hypercore-protocol/) methods
   * [`stream.setTimeout(ms, ontimeout)`](https://github.com/mafintosh/hypercore-protocol#streamsettimeoutms-ontimeout)
   * [`stream.on('timeout', cb)`](https://github.com/mafintosh/hypercore-protocol#streamontimeout)

**Comment by telamon** [comment]
Um. i've been working on upgrading the replication to proto7 since last week, you should be able to simply upgrade hypercore dependency to v8 once [multifeed pr#32](https://github.com/kappa-db/multifeed/pull/32) is merged and my working branch [replication#proto7](https://github.com/telamon/replic8/tree/proto7) is merged.

**Comment by cblgh** [comment]
ohhh that's great news, yr wonderful @telamon ^_^

**Comment by noffle** [comment]
`hypercore-protocol@6.x.x` implements a ping & timeout feature already:

https://github.com/mafintosh/hypercore-protocol/blob/v6.12.0/index.js#L61

Does this not currently work?

**Comment by cblgh** [comment]
Ah, I missed that. I was only diffing hypercore-protocol and its past
version!

**Comment by noffle** [comment]
I *think* this ok now that we're on hypercore 8? It sends keep-alive messages every 10s by default.
