### ISSUE TITLE
Add destroy method

### ISSUE THREAD

**Issue by cblgh** [cabal-club/cabal-core#73]
now that we're using hyperswarm we should ideally try to clean up properly. 

it looks like we should call the (undocumented) `hyperswarm.destroy(cb)` function: [hyperswarm/swarm.js#L294 ](https://github.com/hyperswarm/hyperswarm/blob/master/swarm.js#L294). iirc maf said it was important to wait until the passed-in callback has fired, so as to not muddy up the dht. 

i think it would also be good for cabal-client/cabal-desktop to properly kill all of the processes?

**Comment by cblgh** [comment]
note to self: document `hyperswarm.destroy(cb)` in hyperswarm's README, to help others ^_^

**Comment by okdistribute** [comment]
This ought be part of a `close` or `destroy` method in cabal-core, which would then be called in the clients upon exit.

**Comment by cblgh** [comment]
added in https://github.com/cabal-club/cabal-core/commit/d121e6baa31f7cc660678615811b11f5ec465835

thanks @noffle 🖤
