### ISSUE TITLE
Unknown users are joining private cabals

### ISSUE THREAD

**Issue by rinchen** [cabal-club/cabal-core#82]
I have a bunch of private cabals that have never been published to the public. There are people that appear to be intercepting the swarm messages and joining them.  I've attached some screenshots. 

<img width="319" alt="Screen Shot 2020-05-14 at 08 45 18" src="https://user-images.githubusercontent.com/44416/81948744-4f4d9c80-95bf-11ea-962a-22f92cc4e86d.png">
<img width="319" alt="Screen Shot 2020-05-14 at 08 45 24" src="https://user-images.githubusercontent.com/44416/81948747-4fe63300-95bf-11ea-9f3b-5cb3666c2647.png">

**Comment by cblgh** [comment]
x-post from my message in the public cabal:
i think it's more likely that there's a rendering bug in desktop.  what does it look like if you join yr private cabal with the cli tool?

**Comment by noffle** [comment]
You can check if this is in the database or not, by looking in the directory `~/.cabal/v1/archives/$CABAL_KEY/` and search all of the `data` files for the string for the nickname of the user that's appearing in the private cabals.

**Comment by rinchen** [comment]
@noffle Totally awesome. Thank you. `grep -r '"name":' *` was helpful and I found no entries for these thus @cblgh must be correct that it's a cabal-desktop display issue.

**Comment by noffle** [comment]
*ohthankgoodness*

**Comment by rinchen** [comment]
I'll move this over to Desktop. I'm going to let my cli sessions run overnight and check just to be certain.
