### ISSUE TITLE
Rename to cabal-core

### ISSUE THREAD

**Issue by noffle** [cabal-club/cabal-core#9]
Hey friends @cblgh @nikolaiwarner @ralphtheninja, any objections to me renaming this repo to cabal-core? I think it will be clearer that this is the backend and not the client.

**Comment by nikolaiwarner** [comment]
i've been secretly calling it this for a while LOL

**Comment by ralphtheninja** [comment]
Do it! :)

**Comment by noffle** [comment]
I did it.

TODO: patch the clients to depend on it
- [ ] cabal
- [ ] cabal-desktop
- [ ] cabal-mobile

**Comment by noffle** [comment]
All done.
