### ISSUE TITLE
Specify a default listening port

### ISSUE THREAD

**Issue by NuSkooler** [cabal-club/cabal-core#98]
When using Cabal behind a firewall/NAT environment, we need a way to specify explicit listening port or port ranges such that they can be allowed through. For example, my setup looks like this:

```
{ internet } <--> pfSense firewall <--> CentOS 7 firewalld <--> cabal
```

I must NAT through the firewall and open up a port(s) at firewalld as well.

As instructed in chat, a starting point is simply patching `swarm.js`:
```
`hyperswarm({ preferredPort: 49737 })`
```

This does the trick as a test. However, a configurable set of port/port ranges would be better to allow for conflicts/etc. I would submit a PR but I just started poking around with this yesterday and don't know the code base yet 😅

**Comment by cblgh** [comment]
thanks for making the issue @NuSkooler! i like the following way of solving this:
* choosing a default port and setting it in [swarm.js](https://github.com/cabal-club/cabal-core/blob/master/swarm.js#L19)
  * let's make sure to choose a port number that does not conflict with beaker or hyperdivision's projects & products (as there is a chance of overlap in users for cabal & beaker :)
* allow passing in a port option to cabal-core, which overriding the default port
* add a `--port` option to [cabal-cli](https://github.com/cabal-club/cabal-cli/) to make it easy for people to use in practice

**Comment by noffle** [comment]
This could also be a useful thing to support in cabal's `config.yml`
