### ISSUE TITLE
Suggestion: make it clear which is the main repo to track

### ISSUE THREAD

**Issue by transitive-bullshit** [cabal-club/cabal-core#99]
Just discovered Cabal, and I have to say it looks amazing all around!

My only minor suggestion is that I want to star something to keep it in mind and follow its progress, but the lack of a central `cabal-club/cabal` repo for the project as a whole makes it difficult to infer what I should be following.

If this were SEO, it's like your project has multiple domains `cabal-core`, `cabal-cli`, etc as opposed to a single canonical domain.

Just think it could help cabal grow and reach more people.

On the technical side, I have nothing to contribute haha -- Keep up the great work pushing the boundaries of decentralized chat! 🔥

**Comment by hackergrrl** [comment]
Thanks! Hopefully this is less of a problem now that github has repo pages: https://github.com/cabal-club/
